import { z } from 'zod';
export declare const createMemberSchema: z.ZodObject<{
    firstName: z.ZodString;
    lastName: z.ZodString;
    email: z.ZodOptional<z.ZodString>;
    phone: z.ZodOptional<z.ZodString>;
    address: z.ZodOptional<z.ZodString>;
    city: z.ZodOptional<z.ZodString>;
    state: z.ZodOptional<z.ZodString>;
    zipCode: z.ZodOptional<z.ZodString>;
    birthDate: z.ZodOptional<z.ZodString>;
    baptismDate: z.ZodOptional<z.ZodString>;
    membershipDate: z.ZodOptional<z.ZodString>;
    maritalStatus: z.ZodOptional<z.ZodEnum<["SOLTERO", "CASADO", "DIVORCIADO", "VIUDO", "UNION_LIBRE"]>>;
    gender: z.ZodOptional<z.ZodEnum<["MASCULINO", "FEMENINO", "OTRO", "PREFIERO_NO_DECIR"]>>;
    occupation: z.ZodOptional<z.ZodString>;
    photo: z.ZodOptional<z.ZodString>;
    notes: z.ZodOptional<z.ZodString>;
    ministryId: z.ZodOptional<z.ZodString>;
    spiritualGifts: z.ZodOptional<z.ZodArray<z.ZodString, "many">>;
    secondaryGifts: z.ZodOptional<z.ZodArray<z.ZodString, "many">>;
    spiritualCalling: z.ZodOptional<z.ZodString>;
    ministryPassion: z.ZodOptional<z.ZodArray<z.ZodString, "many">>;
    experienceLevel: z.ZodOptional<z.ZodNumber>;
    leadershipReadiness: z.ZodOptional<z.ZodNumber>;
    skillsMatrix: z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodAny>>;
    personalityType: z.ZodOptional<z.ZodString>;
    transportationOwned: z.ZodOptional<z.ZodBoolean>;
    childcareAvailable: z.ZodOptional<z.ZodBoolean>;
    emergencyContact: z.ZodOptional<z.ZodString>;
}, "strip", z.ZodTypeAny, {
    firstName: string;
    lastName: string;
    email?: string | undefined;
    notes?: string | undefined;
    phone?: string | undefined;
    address?: string | undefined;
    city?: string | undefined;
    state?: string | undefined;
    zipCode?: string | undefined;
    birthDate?: string | undefined;
    baptismDate?: string | undefined;
    membershipDate?: string | undefined;
    maritalStatus?: "SOLTERO" | "CASADO" | "DIVORCIADO" | "VIUDO" | "UNION_LIBRE" | undefined;
    gender?: "MASCULINO" | "FEMENINO" | "OTRO" | "PREFIERO_NO_DECIR" | undefined;
    occupation?: string | undefined;
    photo?: string | undefined;
    ministryId?: string | undefined;
    spiritualGifts?: string[] | undefined;
    secondaryGifts?: string[] | undefined;
    spiritualCalling?: string | undefined;
    ministryPassion?: string[] | undefined;
    experienceLevel?: number | undefined;
    leadershipReadiness?: number | undefined;
    skillsMatrix?: Record<string, any> | undefined;
    personalityType?: string | undefined;
    transportationOwned?: boolean | undefined;
    childcareAvailable?: boolean | undefined;
    emergencyContact?: string | undefined;
}, {
    firstName: string;
    lastName: string;
    email?: string | undefined;
    notes?: string | undefined;
    phone?: string | undefined;
    address?: string | undefined;
    city?: string | undefined;
    state?: string | undefined;
    zipCode?: string | undefined;
    birthDate?: string | undefined;
    baptismDate?: string | undefined;
    membershipDate?: string | undefined;
    maritalStatus?: "SOLTERO" | "CASADO" | "DIVORCIADO" | "VIUDO" | "UNION_LIBRE" | undefined;
    gender?: "MASCULINO" | "FEMENINO" | "OTRO" | "PREFIERO_NO_DECIR" | undefined;
    occupation?: string | undefined;
    photo?: string | undefined;
    ministryId?: string | undefined;
    spiritualGifts?: string[] | undefined;
    secondaryGifts?: string[] | undefined;
    spiritualCalling?: string | undefined;
    ministryPassion?: string[] | undefined;
    experienceLevel?: number | undefined;
    leadershipReadiness?: number | undefined;
    skillsMatrix?: Record<string, any> | undefined;
    personalityType?: string | undefined;
    transportationOwned?: boolean | undefined;
    childcareAvailable?: boolean | undefined;
    emergencyContact?: string | undefined;
}>;
export declare const updateMemberSchema: z.ZodObject<{
    firstName: z.ZodOptional<z.ZodString>;
    lastName: z.ZodOptional<z.ZodString>;
    email: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    phone: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    address: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    city: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    state: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    zipCode: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    birthDate: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    baptismDate: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    membershipDate: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    maritalStatus: z.ZodOptional<z.ZodOptional<z.ZodEnum<["SOLTERO", "CASADO", "DIVORCIADO", "VIUDO", "UNION_LIBRE"]>>>;
    gender: z.ZodOptional<z.ZodOptional<z.ZodEnum<["MASCULINO", "FEMENINO", "OTRO", "PREFIERO_NO_DECIR"]>>>;
    occupation: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    photo: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    notes: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    ministryId: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    spiritualGifts: z.ZodOptional<z.ZodOptional<z.ZodArray<z.ZodString, "many">>>;
    secondaryGifts: z.ZodOptional<z.ZodOptional<z.ZodArray<z.ZodString, "many">>>;
    spiritualCalling: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    ministryPassion: z.ZodOptional<z.ZodOptional<z.ZodArray<z.ZodString, "many">>>;
    experienceLevel: z.ZodOptional<z.ZodOptional<z.ZodNumber>>;
    leadershipReadiness: z.ZodOptional<z.ZodOptional<z.ZodNumber>>;
    skillsMatrix: z.ZodOptional<z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodAny>>>;
    personalityType: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    transportationOwned: z.ZodOptional<z.ZodOptional<z.ZodBoolean>>;
    childcareAvailable: z.ZodOptional<z.ZodOptional<z.ZodBoolean>>;
    emergencyContact: z.ZodOptional<z.ZodOptional<z.ZodString>>;
}, "strip", z.ZodTypeAny, {
    email?: string | undefined;
    notes?: string | undefined;
    phone?: string | undefined;
    firstName?: string | undefined;
    lastName?: string | undefined;
    address?: string | undefined;
    city?: string | undefined;
    state?: string | undefined;
    zipCode?: string | undefined;
    birthDate?: string | undefined;
    baptismDate?: string | undefined;
    membershipDate?: string | undefined;
    maritalStatus?: "SOLTERO" | "CASADO" | "DIVORCIADO" | "VIUDO" | "UNION_LIBRE" | undefined;
    gender?: "MASCULINO" | "FEMENINO" | "OTRO" | "PREFIERO_NO_DECIR" | undefined;
    occupation?: string | undefined;
    photo?: string | undefined;
    ministryId?: string | undefined;
    spiritualGifts?: string[] | undefined;
    secondaryGifts?: string[] | undefined;
    spiritualCalling?: string | undefined;
    ministryPassion?: string[] | undefined;
    experienceLevel?: number | undefined;
    leadershipReadiness?: number | undefined;
    skillsMatrix?: Record<string, any> | undefined;
    personalityType?: string | undefined;
    transportationOwned?: boolean | undefined;
    childcareAvailable?: boolean | undefined;
    emergencyContact?: string | undefined;
}, {
    email?: string | undefined;
    notes?: string | undefined;
    phone?: string | undefined;
    firstName?: string | undefined;
    lastName?: string | undefined;
    address?: string | undefined;
    city?: string | undefined;
    state?: string | undefined;
    zipCode?: string | undefined;
    birthDate?: string | undefined;
    baptismDate?: string | undefined;
    membershipDate?: string | undefined;
    maritalStatus?: "SOLTERO" | "CASADO" | "DIVORCIADO" | "VIUDO" | "UNION_LIBRE" | undefined;
    gender?: "MASCULINO" | "FEMENINO" | "OTRO" | "PREFIERO_NO_DECIR" | undefined;
    occupation?: string | undefined;
    photo?: string | undefined;
    ministryId?: string | undefined;
    spiritualGifts?: string[] | undefined;
    secondaryGifts?: string[] | undefined;
    spiritualCalling?: string | undefined;
    ministryPassion?: string[] | undefined;
    experienceLevel?: number | undefined;
    leadershipReadiness?: number | undefined;
    skillsMatrix?: Record<string, any> | undefined;
    personalityType?: string | undefined;
    transportationOwned?: boolean | undefined;
    childcareAvailable?: boolean | undefined;
    emergencyContact?: string | undefined;
}>;
//# sourceMappingURL=member.d.ts.map